### ISSUE TITLE
npm package not available

### ISSUE THREAD

**Issue by raman-lsq-1** [featbit/openfeature-provider-js-client#4]
![310421196-aeea5f4d-81f0-4097-882f-257ec5f2f1cd](https://github.com/featbit/openfeature-provider-js-client/assets/162427402/fd96803b-a825-4d1b-b7d9-27be21808448)

**Comment by cosmos-explorer** [comment]
@raman-lsq-1 Sorry for the late reply, this was a typo in the readme file, we just fixed it and published a new version of the package.
